"""empty message

Revision ID: 269292b8628d
Revises: 2d9d8f4b00c5
Create Date: 2015-11-17 23:41:29.110105

"""

# revision identifiers, used by Alembic.
revision = '269292b8628d'
down_revision = '2d9d8f4b00c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'user', sa.Column('team_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'user_org_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'team', ['team_id'], ['id'])
    op.drop_column(u'user', 'org_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(u'user_org_id_fkey', 'user', 'org', ['org_id'], ['id'])
    op.drop_column(u'user', 'team_id')
    op.drop_table('team')
    ### end Alembic commands ###
